CREATE TABLE [User] (
	ID int NOT NULL,
	Name nvarchar(250) NOT NULL,
	Surname nvarchar(250) NOT NULL,
	Patronymic nvarchar(250),
	DateOfBirth datetime NOT NULL,
	Login varchar(25) NOT NULL UNIQUE,
	Password varchar(1200) NOT NULL,
	ImageID int NOT NULL,
	RoleID int NOT NULL,
  CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Award] (
	ID int NOT NULL,
	Title nvarchar(25) NOT NULL UNIQUE,
	ImageID int NOT NULL,
  CONSTRAINT [PK_AWARD] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Image] (
	ID int NOT NULL,
	Image varbinary(MAX) NOT NULL,
  CONSTRAINT [PK_IMAGE] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [UsersAwards] (
	UserID int NOT NULL,
	AwardID int NOT NULL
)
GO
CREATE TABLE [Role] (
	ID int NOT NULL,
	RoleName varchar(30) NOT NULL UNIQUE,
  CONSTRAINT [PK_ROLE] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
ALTER TABLE [User] WITH CHECK ADD CONSTRAINT [User_fk0] FOREIGN KEY ([ImageID]) REFERENCES [Image]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [User] CHECK CONSTRAINT [User_fk0]
GO
ALTER TABLE [User] WITH CHECK ADD CONSTRAINT [User_fk1] FOREIGN KEY ([RoleID]) REFERENCES [Role]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [User] CHECK CONSTRAINT [User_fk1]
GO

ALTER TABLE [Award] WITH CHECK ADD CONSTRAINT [Award_fk0] FOREIGN KEY ([ImageID]) REFERENCES [Image]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Award] CHECK CONSTRAINT [Award_fk0]
GO


ALTER TABLE [UsersAwards] WITH CHECK ADD CONSTRAINT [UsersAwards_fk0] FOREIGN KEY ([UserID]) REFERENCES [User]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [UsersAwards] CHECK CONSTRAINT [UsersAwards_fk0]
GO
ALTER TABLE [UsersAwards] WITH CHECK ADD CONSTRAINT [UsersAwards_fk1] FOREIGN KEY ([AwardID]) REFERENCES [Award]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [UsersAwards] CHECK CONSTRAINT [UsersAwards_fk1]
GO


